import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const sharp=createRequire(import.meta.url)('../../../.tools-node/node_modules/sharp');
const root=path.resolve(import.meta.dirname,'../../..');const cycle=path.basename(import.meta.dirname);const A=`assets/motion/${cycle}`;const W=`build/video/${cycle}/work`;const R=`build/reels/${cycle}/work`;
for(const dir of [W,R])fs.mkdirSync(path.join(root,dir),{recursive:true});
const svg=(w,h,s)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">${s}</svg>`;
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');
const png=async(file,w,h,s)=>{await sharp(Buffer.from(svg(w,h,s))).png().toFile(path.join(root,file));return file;};
const top=async(name,text)=>png(`${W}/${name}.png`,1920,1080,`<rect x="65" y="45" width="1500" height="135" rx="24" fill="#061b23" fill-opacity=".62"/><text x="100" y="132" font-family="Arial" font-size="48" font-weight="bold" fill="white">${esc(text)}</text>`);
const titles={m1:await top('m1-title','YOUR MAP CAN SHOW A FALSE LOCATION'),m2:await top('m2-title','ONE ECG LEAD, CLUES TO HEART FUNCTION'),teaser:await top('teaser','NEXT: WHAT ONE ECG LEAD CAN REVEAL')};
const tag=async(name,text,credit)=>png(`${W}/${name}.png`,1920,1080,`<rect x="70" y="205" width="1180" height="60" rx="14" fill="#061b23" fill-opacity=".63"/><text x="95" y="246" font-family="Arial" font-size="27" fill="white">${esc(text)}</text><text x="70" y="1030" font-family="Arial" font-size="23" fill="white" stroke="#061b23" stroke-width="3" paint-order="stroke">${esc(credit)}</text>`);
const tags={current:await tag('current','JAMMERTEST • SEPTEMBER 2026','©ESA/jensenmedia'),archive:await tag('archive','ARCHIVE • SEPTEMBER 2025 • NOT THE 2026 TESTS','©European Space Agency (ESA) • source frame cropped'),context:await tag('context','CONTEXT FOOTAGE • NOT STUDY PARTICIPANTS OR STUDIED DEVICE','Healthcare stock • Pexels • full credits in CREDITS.md'),figure:await tag('figure','STUDY FIGURE • RETROSPECTIVE, SINGLE-CENTRE RESEARCH','van der Valk et al. (2026) • CC BY 4.0 • original figure cropped/scaled')};
const closing=await png(`${W}/closing.png`,1920,1080,'<defs><linearGradient id="g"><stop stop-color="#041820"/><stop offset="1" stop-color="#125867"/></linearGradient></defs><rect width="1920" height="1080" fill="url(#g)"/><rect x="380" y="265" width="1160" height="550" rx="48" fill="white" fill-opacity=".10" stroke="white" stroke-opacity=".2"/><text x="960" y="470" text-anchor="middle" fill="white" font-family="Arial" font-size="72" font-weight="bold">LIKE • SUBSCRIBE</text><text x="960" y="565" text-anchor="middle" fill="#a0f2e2" font-family="Arial" font-size="42">Stay with science.</text><rect x="690" y="630" width="540" height="84" rx="42" fill="#ff5968"/><text x="960" y="687" text-anchor="middle" fill="white" font-family="Arial" font-size="34" font-weight="bold">SUBSCRIBE</text>');
const bell=await png(`${W}/closing-bell.png`,180,180,'<path d="M90 24c-28 0-46 22-46 54v31l-15 22h122l-15-22V78c0-32-18-54-46-54Z" fill="#ffe36b"/><circle cx="90" cy="145" r="15" fill="#ffe36b"/>');
const S=(file,duration,label='current',extra={})=>({kind:'still',file:`${A}/main/${file}`,duration,label,overlay:tags[label],...extra});
const V=(file,duration,seek=0,label='context',extra={})=>({kind:'motion',file:`${A}/main/${file}`,duration,seek,label,overlay:tags[label],loop:false,...extra});
const E=(duration,seek)=>V('m1/jammertest-2025-source.mp4',duration,seek,'archive',{crop:'1920:800:0:0'});
const sections=[{id:'m1',duration:160,audio:`build/video/${cycle}/audio/m1.wav`,counts:{stills:5,motion:8,secondStoryTeaser:1},scenes:[S('m1/esa-1.jpg',5,'current',{title:titles.m1}),E(7,52),V('m2/pexels-8026528.mp4',4,2,'context',{title:titles.teaser}),S('m1/esa-0.jpg',14),E(11,59),E(14,80),S('m1/esa-3.jpg',14),E(14,104),E(15,118),S('m1/esa-2.png',14),E(9,140),E(15,166),S('m1/esa-4.jpg',14),E(10,190)]},
{id:'m2',duration:140,audio:`build/video/${cycle}/audio/m2.mp3`,counts:{stills:4,motion:6},scenes:[V('m2/pexels-8460066.mp4',12,0,'context',{title:titles.m2}),V('m2/pexels-8311312.mp4',11),V('m2/pexels-8026528.mp4',14),V('m2/pexels-7088462.mp4',16),S('m2/fig5-monitoring.png',15,'figure'),S('m2/fig6-processing.png',14,'figure'),S('m2/fig1-roc.png',16,'figure'),S('m2/fig2-aggregation.png',14,'figure'),V('m2/pexels-8413638.mp4',14),V('m2/pexels-7195664.mp4',14)]},
{id:'closing',duration:10,audio:`build/video/${cycle}/audio/closing.mp3`,closing:true}];
const hashInputs=m=>{const files=[...new Set(m.flatMap(s=>s.file))];return Object.fromEntries(files.map(f=>[f,createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));};
const main={cycle,status:'prepared-for-review',candidateOutput:`build/video/${cycle}/newhorizons.mp4`,finalOutput:'build/video/newhorizons.mp4',duration:310,fps:60,width:1920,height:1080,sections,closing,closingBell:bell,titleDisplaySeconds:4,hashes:hashInputs(sections.flatMap(s=>s.scenes||[]))};
fs.writeFileSync(path.join(root,`video/cycles/${cycle}/main_manifest.json`),JSON.stringify(main,null,2)+'\n');
const cfg={r1:{title:['CAN AI IMPROVE','HOSPITAL HANDOFFS?'],files:['pexels-6997946.mp4','pexels-5998403-still.png','pexels-36656061.mp4','pexels-5453568-still.png','pexels-5998403.mp4','pexels-6997946-still.png','pexels-5453568.mp4'],output:'01-ai-hospital-handoffs.mp4'},r2:{title:['WHEN A WILDFIRE','BUILDS A STORM'],files:['inspyre-pyrocb-diagram.png','inspyre-preview-loiacono-9318.jpg','inspyre-news-image-7-28-26-4.jpeg','inspyre-light-walk.mp4','afrc2026-0144-226orig-er2-inst.jpg','inspyre-preview-loiacono-0172.jpg','inspyre-light-walk.mp4'],output:'02-wildfire-storms.mp4'}};
for(const [id,c]of Object.entries(cfg)){
 const title=await png(`${R}/${id}-title.png`,1080,1920,`<rect x="50" y="155" width="980" height="270" rx="30" fill="#061b23" fill-opacity=".64"/><text x="90" y="280" fill="white" font-family="Arial" font-size="53" font-weight="bold">${c.title[0]}</text><text x="90" y="355" fill="white" font-family="Arial" font-size="53" font-weight="bold">${c.title[1]}</text>`);
 const cta=await png(`${R}/${id}-cta.png`,1080,1920,'<text x="540" y="1585" text-anchor="middle" fill="white" stroke="#061b23" stroke-width="5" paint-order="stroke" font-family="Arial" font-size="37" font-weight="bold">YouTube @newhorizons_21</text><text x="540" y="1645" text-anchor="middle" fill="white" stroke="#061b23" stroke-width="5" paint-order="stroke" font-family="Arial" font-size="35" font-weight="bold">Instagram • Like &amp; Follow</text>');
 const sources=JSON.parse(fs.readFileSync(path.join(root,`video/cycles/${cycle}/media_sources.json`)));
 const scenes=[];
 for(let i=0;i<c.files.length;i++){
  const file=`${A}/reels/${id}/${c.files[i]}`;const a=sources.find(a=>a.file===file);let label=id==='r1'?'CONTEXT • NOT STUDY PARTICIPANTS':i===0?'SCIENTIFIC DIAGRAM • NOT A PHOTOGRAPH':'INSPYRE • SUMMER 2026 CAMPAIGN';
  let credit=id==='r1'?'Healthcare stock • Pexels':a.credit;
  const detail=await png(`${R}/${id}-detail-${i}.png`,1080,1920,`<rect x="90" y="480" width="900" height="65" rx="16" fill="#061b23" fill-opacity=".64"/><text x="540" y="521" text-anchor="middle" font-family="Arial" font-size="27" fill="white">${esc(label)}</text><text x="540" y="1408" text-anchor="middle" font-family="Arial" font-size="23" fill="white" stroke="#061b23" stroke-width="3" paint-order="stroke">${esc(credit)}</text>`);
  scenes.push({kind:file.endsWith('.mp4')?'motion':'still',file,duration:i===6?9:6,seek:id==='r2'&&i===6?7:0,loop:false,label,overlay:detail});
 }
 const m={cycle,status:'prepared-for-review',output:`build/reels/${cycle}/${c.output}`,audio:`build/video/${cycle}/audio/${id}.mp3`,overlay:title,ctaOverlay:cta,ctaStartInFinalScene:6,duration:45,fps:60,width:1080,height:1920,counts:{stills:scenes.filter(s=>s.kind==='still').length,motion:scenes.filter(s=>s.kind==='motion').length},scenes,hashes:hashInputs(scenes)};
 fs.writeFileSync(path.join(root,`video/cycles/${cycle}/${id}_manifest.json`),JSON.stringify(m,null,2)+'\n');
}
console.log('Cycle overlays and manifests prepared.');
